### ISSUE TITLE
Extreme solving times due to mallocs in ticketlock.c and mutex-musl.c

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#132]
The lock benchmarks ```ticketlock-6.c``` and ```mutex-musl-4``` (and their derivations) take a lot time for the outer solver when doing ```Refinement```. We don't observe such a huge time spent in the outer solver on any other lock benchmarks.

The difference between these two benchmarks and all the other ones is that both of them have a two-member struct of the form
``` 
struct lock {
   atomic_int a;
   atomic_int b;
} 
```
whereas the other one's have only one-member structs. Unfortunately, as soon as we have two-member structs, we need to malloc instances of the lock and cannot simply declare them globally (this is caused by an issue between the SMACK-generated code and our Alias analysis). It seems this malloc causes huge performance degradation.

If we manually unpack that struct into two globals ```atomic_int a``` and ```atomic_int b``` and simply pass those around, we can avoid the malloc and the solving times increase drastically (possibly 2 orders of magnitude).

It is not clear why the performance difference is this drastic but we suspect two reasons:
- Without the malloc, we have less addresses and our analysis gets more precise. We should end up with smaller max-sets for co and rf.
- We completely avoid pointer arithmetic to access members. The solver may more easily fall back into pure equality reasoning.

I don't have any solutions to this in mind right now though.

**Comment by ThomasHaas** [comment]
I did a quick test on `ticketlock-6.c` to compare the `malloc` version and the `unpacked` version.
`malloc`-version:
- maxTupleSet size for co: 1290
- maxTupleSet size for rf: 1639

`unpacked`-version:
- maxTupleSet size for co: 158
- maxTupleSet size for rf: 174

So we are roughly an order of magnitude more accurate without the malloc. This is not caused by the additional intermediate addresses but by the inaccuracy of our pointer analysis. If I manually change the `malloc(8)` to a `malloc(2)` to only allocated space for the 2 members without any intermediate addresses, the max-sets only reduce by about 100 events.

**Comment by hernanponcedeleon** [comment]
Solved by f10092f76725db4edee5bb4a9cceab67a2eda3e9.

**Comment by ThomasHaas** [comment]
Let me add that this is solved by now avoiding `malloc` altogether. Our mallocs still cause a lot of imprecision that we should deal with eventually.

**Comment by hernanponcedeleon** [comment]
You are right! changing the benchmarks is different than solving the problem.
Since the description mentions a benchmark that was modified, here is the code that was causing performance problems.
```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <pthread.h>
#include <stdatomic.h>
#include <assert.h>

// ticketlock.h
//
struct ticketlock_s {
    atomic_int next;
    atomic_int owner;
};
typedef struct ticketlock_s ticketlock_t;

static inline void ticketlock_init(struct ticketlock_s *l);
static inline void ticketlock_acquire(struct ticketlock_s *l);
static inline int ticketlock_tryacquire(struct ticketlock_s *l);
static inline void ticketlock_release(struct ticketlock_s *l);

// ticketlock.c
//
static inline void ticketlock_init(struct ticketlock_s *l)
{
    atomic_init(&l->next, 0);
    atomic_init(&l->owner, 0);
}

static inline int get_next_ticket(struct ticketlock_s *l)
{
    return atomic_fetch_add_explicit(&l->next, 1, memory_order_relaxed);
}

static inline void await_for_ticket(struct ticketlock_s *l, int ticket)
{
    while (atomic_load_explicit(&l->owner, memory_order_acquire) != ticket)
        ;
}

static inline void ticketlock_acquire(struct ticketlock_s *l)
{
    int ticket = get_next_ticket(l);
    await_for_ticket(l, ticket);
}

// NOTE: Unused and wrong code!
static inline int ticketlock_tryacquire(struct ticketlock_s *l)
{
    int o = atomic_load_explicit(&l->owner, memory_order_acquire);
    int n = atomic_compare_exchange_strong_explicit(&l->next, &o, o + 1,
                            memory_order_relaxed,
                            memory_order_relaxed);
    return n == o;
}

static inline void ticketlock_release(struct ticketlock_s *l)
{
    int owner = atomic_load_explicit(&l->owner, memory_order_relaxed);
    atomic_store_explicit(&l->owner, owner + 1, memory_order_release);
}

// main.c
//
int shared;
ticketlock_t *lock;

void *thread_n(void *arg)
{
    intptr_t index = ((intptr_t) arg);

    ticketlock_acquire(lock);
    shared = index;
    int r = shared;
    assert(r == index);
    ticketlock_release(lock);
    return NULL;
}

// variant
//
int main()
{
    pthread_t t0, t1, t2, t3, t4, t5;

    lock = malloc(sizeof(ticketlock_t));
    ticketlock_init(lock);
    
    pthread_create(&t0, NULL, thread_n, (void *) 0);
    pthread_create(&t1, NULL, thread_n, (void *) 1);
    pthread_create(&t2, NULL, thread_n, (void *) 2);
    pthread_create(&t3, NULL, thread_n, (void *) 3);
    pthread_create(&t4, NULL, thread_n, (void *) 4);
    pthread_create(&t5, NULL, thread_n, (void *) 5);
    
    return 0;
}
```

**Comment by ThomasHaas** [comment]
After a discussion with @hernanponcedeleon, we found that the `malloc` code actually creates store to `lock` and then reloads `lock` to pass it to `ticketlock_init` which causes the whole alias analysis to fail.
Looking that the code, this makes sense.
I'm wondering what happens if we avoid the global `lock` altogether and do this:
```
    ticketlock_t *lock = malloc(sizeof(ticketlock_t));
    ticketlock_init(lock);
 ```
 This way, the pointer does not get stored and then reloaded from `lock`. This should result in the same performance we have with static allocation I believe.

**Comment by hernanponcedeleon** [comment]
Based on the last comment above, the poor performance is due to having more events. @ThomasHaas can we close?

**Comment by ThomasHaas** [comment]
Yes, we can close this. Our benchmarks have changed so the issue is gone.
