### ISSUE TITLE
Abstraction/Usage of Alias Analysis

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#137]
Our current alias analysis is used in a very specific manner:
- It is created by the `Wmm` on initialization
- It computes address sets and attaches them to `MemEvents`

This usage pattern forces the alias analysis to be based on address sets. This is unnecessarily restrictive and forbids most advanced types of analysis.
Instead, we should treat the alias analysis just like we treat our `BranchEquivalence`. It gets instantiated once on/before initialization and is then accessible via the `VerificationTask` object. The alias analysis object should provide simple methods to check aliasing information: `mayAlias(e1, e2)`, `mustAlias(e1, e2)` and possibly more if needed.
During the encoding phase, all relevant objects have access to the `task` object, so we can easily use e.g. `task.getAliasAnalysis().mayAlias(e1, e2)` instead of relying on the fact that the `MemEvents` `e1` and `e2` themselves contain any aliasing information. This gives us the freedom to replace our current analysis by any other analysis in a modular manner.

**Comment by hernanponcedeleon** [comment]
This issue is solved in `config` and can be closed once that PR is merged, right @ThomasHaas ?

**Comment by ThomasHaas** [comment]
Yes, this is solved
