### ISSUE TITLE
LISA parser

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#138]
[Here](https://github.com/paulmckrcu/litmus) there is a large corpus of litmus test for the LKMM.
Half of them are probably the ones we have in our test suite, however the are half we cannot currently handle because we do not have a parser for LISA.
We should implement this to have a larger set of LKMM tests.

**Comment by ThomasHaas** [comment]
We have to double-check that these tests are actually valid for our current LKMM. The repo has various different definitions of the memory model (5 versions I think) that all differ from our current model I believe. So "wrong results" in some tests might be caused by differing memory models.

**Comment by hernanponcedeleon** [comment]
We compare our results with those generated by herd, so as long as we run both tools with the same models, this should not be a problem.

**Comment by hernanponcedeleon** [comment]
[This](https://github.com/herd/herdtools7/blob/b86aec8db64f8812e19468893deb1cdf5bbcfb83/litmus/LISACompile.ml#L92) needs to be used as a resource to understand the semantics of the LISA instructions.

**Comment by hernanponcedeleon** [comment]
I pushed a branch with the implementation of the parser. The parser is yet not complete, but currently we can parse and verify (w.r.t our usual LKMM cat file) ~4000 new tests.

The problem is that I did not manage yet to make herd work with these tests (apparently herd requires some configuration file to be able to understand the semantics of the instructions) so I could not create the expected results to test if the parser is correct.

**Comment by hernanponcedeleon** [comment]
I manage to make herd work for around half of the tests (2387). From those, two parsing problems remains. There is also one wrong result which I think it is related to control dependency yes. This is the program
```
LISA WWC+o-branch-o+o-branch-o
(* Allowed: Control dependencies not transitive.  Also allowed by PowerPC. *)
{
x = 0;
y = 0;
}
P0               | P1               | P2          ;
r[once] r1 x     | r[once] r2 y     | w[once] x 2 ;
mov r3 (eq r1 0) | mov r4 (eq r2 0) |             ;
b[] r3 END1      | b[] r4 END2      |             ;
w[once] y 1      | w[once] x 1      |             ;
END1:            | END2:            |             ;
exists(0:r1=2 /\ 1:r2=1 /\ x = 2)
```
Interestingly, we also report a wrong result (`PASS`) for `PPC`.

**Comment by ThomasHaas** [comment]
The wrong result on that benchmark seems to be something fundamental with the anarchic semantics. Refinement cannot find any single violation, so even under the empty memory model, we don't find any violation.

I checked `rf`, `co` and `finalRegValues` and the encodings seemed to be fine. I suspect that the benchmark breaks some hidden assumption we have, maybe that there is no jump label as last statement or something like that.

**Comment by hernanponcedeleon** [comment]
The problem with the program mentioned above is independent of the parser, thus I'll create a different issue for it. The PR #210 solves half of this issue since there are still benchmarks that, while we can verify, we cannot yet compare the results with herd. Thus this issue needs to remain open.

**Comment by ThomasHaas** [comment]
The bug of the above code was fixed. The Litmus parser had a nasty bug that inverted both NEQ and the jump conditions which caused all benchmarks that jump according to a NEQ result to be accidentally correct. It seems that the above benchmark is the only one using EQ which made it fail.

**Comment by hernanponcedeleon** [comment]
[Herd does not support LISA anymore](https://github.com/paulmckrcu/litmus/issues/10#issuecomment-1015323233), so there is no point in using all the benchmarks in the linked repo. However, @ThomasHaas and me agreed that it would be useful to have a simple (i.e. it is the role of the user to guarantee that tags in the litmus tests match sets in the cat file; we might potentially implement a check for this) LISA parser to be able to write new tests.

I'll clean up the code of #210 and add some LISA tests for different architectures.
