### ISSUE TITLE
Coherence encoding forces total order over ALL writes

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#140]
I just noticed that our current coherence encoding forces an assignment of distinct integer values to each `Store`. However, such a constraint is only necessary if the `Stores` actually access the same address. We should investigate what happens if we only enforce inequality for same address writes. The encoding might get larger but it might help the solver if he doesn't have to "merge" all total orders per location to a global total order.

**Comment by hernanponcedeleon** [comment]
Implementation-wise I think adding this just before [this](https://github.com/hernanponcedeleon/Dat3M/blob/e9ee03bf179917c0f0cc6292a6d8ad04c9f1c956/dartagnan/src/main/java/com/dat3m/dartagnan/wmm/relation/base/memory/RelCo.java#L128) and removing the previous code adding that the `coVars` are different should do 
```
enc = bmgr.and(enc, bmgr.ifThenElse(imgr.equal(a1, a2), imgr.distinct(Arrays.asList(intVar(term, w1, ctx), intVar(term, w2, ctx))), bmgr.makeTrue()));
```

**Comment by ThomasHaas** [comment]
With the recent changes to the coherence encoding, this is no longer an issue.
