### ISSUE TITLE
Atomicity encoding for atomic blocks is buggy

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#152]
@hernanponcedeleon and me discussed this problem before.
I'm opening this issue so we do not forget. I think one of the weaver benchmarks (test-easy8?) showed this behaviour.

**Comment by xeren** [comment]
This might be caused by the relaxed memory order, if another consistency model than SC is used.  Locks should be at least Acquire-Release.  Can you describe the test that was used?  I never encountered any 'weaver' benchmark.

**Comment by ThomasHaas** [comment]
We know why this is caused. It is simply that our atomicity encoding for atomic blocks (SVCOMP) is incorrect.
I don't have the exact reason in mind right now, but IIRC it had to do with cases where an ordering was not directly caused by a `com` relation between 2 atomic blocks but indirectly over a third thread (via com;po;com).

We have observed this problem in only one benchmark so far, so it is a rather rare problem.
If we replace the atomic blocks by locks, it works as expected.

**Comment by xeren** [comment]
Would that benchmark work on this model?
```
let hb = (po \ rmw) | com
let atomic = rmw | rmw^-1
acyclic hb | (hb ; atomic) | (atomic ; hb)
empty rmw^-1 & com
```

**Comment by ThomasHaas** [comment]
You can check out the benchmark here: [Link](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/weaver/test-easy8.wvr.c)

The benchmark is really short and can be understood by hand. The program is safe as `c=1` will always hold after both threads join (and hence the program aborts before reaching the error). If `thread2` runs last, it is obvious as it does `c=1`. If `thread1` runs last, then it will fail its assume since `thread2` will have set `b=1`.

**Comment by xeren** [comment]
The above model had flaws, but the program was safe under it.  The PR features a modification that should fit the existing tests and `easy8`.

**Comment by hernanponcedeleon** [comment]
The cat files makes sense to me and the CI did not complain. I'll make a run in the server using the whole set of svcomp benchmarks and if all pass, I'll merge
