### ISSUE TITLE
New lock benchmark

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#161]
[This paper](https://arxiv.org/pdf/2111.15240.pdf) present some new lock benchmark which might be interested to see if we can solve.

**Comment by ThomasHaas** [comment]
There is a also a [repo](https://github.com/multicore-locks/litl) that contains some lock implementations.

**Comment by hernanponcedeleon** [comment]
Status update: the user level CNA benchmarks were already merged (65d21052f5a111cee0b23d9663e37c167b8d538f). The variant from the kernel is still WIP.

**Comment by hernanponcedeleon** [comment]
We can already handle the version of CNA from the kernel so this issue can be closed.
