### ISSUE TITLE
mutex relaxations are not live (in benchmarks)

### ISSUE THREAD

**Issue by db7** [hernanponcedeleon/Dat3M#163]
Hi,

nice updates to the tool. It seems to have evolved a lot in the last months.

I was looking at the lock benchmarks, and I think that some of the mutex relaxations (in benchmarks) can bring the code to hang on Arm. For example, `mutex-4-rel2rx-futex` removes [the release barrier](https://github.com/hernanponcedeleon/Dat3M/blob/83ced4245086c93d68d8927ec6c91eb2c84ce062/benchmarks/locks/mutex-4-rel2rx-futex.c#L24) in the `futex_wake`. That allows the store to `sig` to be reordered with the `STXLR` of the `cmpxchg` in the `mutex_unlock_fastpath`. A thread waiting on the futex could awaken, but then fail the `cmpxchg`. Subsequently, it would hang in the futex forever.

Looking at the `expected_veredict` field [here](https://github.com/hernanponcedeleon/Dat3M/blob/master/benchmarks/locks/arm/mutex-4-rel2rx-futex.yml), it seems this is considered to be correct, but it is not.

**Comment by ThomasHaas** [comment]
Thanks for the information. Unfortunately, as for now, we do not check for deadlocks but only for assertion violations. That is why we deem the benchmark to be safe.
Frankly, I'm not sure how easy it is to adapt Dartagnan for deadlock detection. @hernanponcedeleon do you have ideas how to handle this?

**Comment by hernanponcedeleon** [comment]
This is because we cannot yet verify **liveness** (this issue was faster than my answer to your email). Notice that [this](https://github.com/hernanponcedeleon/Dat3M/blob/db8c6253ef73161e9bf742ee5ae587121404b290/benchmarks/locks/arm/mutex-4-rel2rx-futex.yml#L6) explicitly states that this is the expected result for the **reachability** query (i.e. it means that the assertion cannot be violated).

We created those variants with weaker guarantees to have more benchmarks to run the verification on. The expected (reachability) results were generated from the output of our tool and doubled checked with `genmc`, e.g., (this is a version with just 2 threads)
```
genmc -imm benchmarks/locks/mutex_musl-3-rel2rx-futex.c --mo --sr
WARNING: Atomic xchg support is experimental under dependency-tracking models!
Number of complete executions explored: 34
Number of blocked executions seen: 12
Total wall-clock time: 0.02s
```
But you are right, if we use `genmc` to test liveness, the program is actually unsafe
```
genmc -imm benchmarks/locks/mutex_musl-3-rel2rx-futex.c --mo --sr --check-liveness 
WARNING: Atomic xchg support is experimental under dependency-tracking models!
Error detected: Liveness violation!
Event (2, 24) in graph:
<-1, 0> main:
	(0, 0): B
	(0, 1): M L.114
	(0, 2): Wna (mutex, 0x238513f0) L.114
	(0, 3): Rna (mutex, 0x238513f0) [(0, 2)] L.115
	(0, 4): Wna (, 0) L.44
	(0, 5): Wna (, 0) L.45
	(0, 6): TC [forks 1] L.117
	(0, 7): TC [forks 2] L.118
	(0, 8): E
<0, 1> thread_n:
	(1, 0): B
	(1, 1): Rna (mutex, 0x238513f0) [(0, 2)] L.101
	(1, 2): Cacq (, 0) [(0, 4)] L.51
	(1, 3): Cacq (, 1) L.51
	(1, 4): Wna (shared, 0) L.102
	(1, 5): Rna (shared, 0) [(1, 4)] L.103
	(1, 6): Rna (mutex, 0x238513f0) [(0, 2)] L.105
	(1, 7): Urel (, 2) [(2, 9)] L.86
	(1, 8): Urel (, 0) L.86
	(1, 9): Rrlx (, 0) [(0, 5)] L.87
	(1, 10): Urlx (sig, 0) [INIT] L.24
	(1, 11): Urlx (sig, 1) L.24
	(1, 12): E
<0, 2> thread_n:
	(2, 0): B
	(2, 1): Rna (mutex, 0x238513f0) [(0, 2)] L.101
	(2, 2): Cacq (, 1) [(1, 3)] L.51
	(2, 3): LOOP_BEGIN L.71
	(2, 4): SPIN_START
	(2, 5): Cacq (, 1) [(1, 3)] L.59
	(2, 6): Urlx (, 0) [(0, 5)] L.73
	(2, 7): Urlx (, 1) L.73
	(2, 8): Crlx (, 1) [(1, 3)] L.75
	(2, 9): Crlx (, 2) L.75
	(2, 10): Racq (sig, 0) [INIT] L.14
	(2, 11): Racq (, 2) [(2, 9)] L.15
	(2, 12): SPIN_START
	(2, 13): Racq (sig, 1) [(1, 11)] L.18
	(2, 14): Urlx (, 1) [(2, 7)] L.80
	(2, 15): Urlx (, 0) L.80
	(2, 16): SPIN_START
	(2, 17): Cacq (, 2) [(2, 9)] L.59
	(2, 18): Urlx (, 0) [(2, 15)] L.73
	(2, 19): Urlx (, 1) L.73
	(2, 20): Crlx (, 2) [(2, 9)] L.75
	(2, 21): Racq (sig, 1) [(1, 11)] L.14
	(2, 22): Racq (, 2) [(2, 9)] L.15
	(2, 23): SPIN_START
	(2, 24): Racq (sig, 1) [(1, 11)] L.18

Non-terminating spinloop
Number of complete executions explored: 8
Number of blocked executions seen: 2
Total wall-clock time: 0.01s
```

**Comment by hernanponcedeleon** [comment]
> Frankly, I'm not sure how easy it is to adapt Dartagnan for deadlock detection. @hernanponcedeleon do you have ideas how to handle this?

There is [this](https://people.mpi-sws.org/~viktor/papers/oopsla2021-fairness.pdf) paper that is my TODO list, but I haven't find time yet to read it. @db7 do you know if this is what is actually implemented in genmc?

**Comment by db7** [comment]
@ThomasHaas @hernanponcedeleon, thanks for the replies! I think that clarifies my confusion. I will close this issue.

> There is this paper that is my TODO list, but I haven't find time yet to read it. @db7 do you know if this is what is actually implemented in genmc?

Yes.

**Comment by db7** [comment]
> Thanks for the information. Unfortunately, as for now, we do not check for deadlocks but only for assertion violations. That is why we deem the benchmark to be safe.
> Frankly, I'm not sure how easy it is to adapt Dartagnan for deadlock detection.

I have no idea how easy it would be to add that to Dartagnan, but it would make the tool useful for practitioners (at least in the context of locks), because such liveness issues (sometimes) happen on real hardware when too few/weak barriers are used.
