### ISSUE TITLE
Useless barriers in mutex_musl

### ISSUE THREAD

**Issue by db7** [hernanponcedeleon/Dat3M#164]
Hi, I was taking a look at the lock examples and there is this musl mutex there, and it contains a few `atomic_thread_fence(memory_order_relaxed)`, for example, [here](https://github.com/hernanponcedeleon/Dat3M/blob/db8c6253ef73161e9bf742ee5ae587121404b290/benchmarks/locks/mutex_musl-3.c#L69). These are a bit weird. What do you need them?

Also, I am not sure whether the current barriers match the barriers from the [real musl mutex](https://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_mutex_timedlock.c#n56). In particular, the `a_cas` has some extra fence (like LKMM fences after RMW).

**Comment by hernanponcedeleon** [comment]
The benchmarks are adaptations of those from the genmc repository; see e.g., [here](https://github.com/MPI-SWS/genmc/blob/master/tests/correct/data-structures/mutex_musl/mutex_musl.c). 
Initially I took a look to code like [this](https://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_mutex_timedlock.c#n56) but once I realised most of the locks were in the genmc repository, I used that code without really checking if this was faithful to the **real** lock code.

Now that you even raise the topic, those fences (with `memory_order_relaxed`) do not make any sense to me. In our compilation scheme (following [this](https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html)) they do not have any effect. I'm not sure how genmc treats them; based on Figure 5 of [this](http://plv.mpi-sws.org/imm/paper.pdf) it would results in `dmb.sy` but I assume the paper intended to cover the cases `!= acq` **and rx!!!**.

Coming back to the real code, how do `a_inc`, `a_sub` and `a_cas` related to `atomic_fetch_add_explicit`, `atomic_fetch_sub_explicit ` and `atomic_compare_exchange_strong_explicit`? From e.g., [here](https://fossies.org/dox/musl-1.2.2/arm_2atomic__arch_8h_source.html) it seems they are plain inlined assembly. But I don't see how they can handle atomic instructions with different memory orderings, e.g., how do you differentiate `atomic_fetch_add_explicit(&m->waiters, 1, memory_order_relaxed)` from `atomic_fetch_add_explicit(&m->waiters, 1, memory_order_seq_cst)`?

**Comment by db7** [comment]
> The benchmarks are adaptations of those from the genmc repository; see e.g., [here](https://github.com/MPI-SWS/genmc/blob/master/tests/correct/data-structures/mutex_musl/mutex_musl.c). Initially I took a look to code like [this](https://git.musl-libc.org/cgit/musl/tree/src/thread/pthread_mutex_timedlock.c#n56) but once I realised most of the locks were in the genmc repository, I used that code without really checking if this was faithful to the **real** lock code.

Ah! That makes a lot of sense. I was not aware of these locks in genmc!

> Now that you even raise the topic, those fences (with `memory_order_relaxed`) do not make any sense to me. In our compilation scheme (following [this](https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html)) they do not have any effect. I'm not sure how genmc treats them; based on Figure 5 of [this](http://plv.mpi-sws.org/imm/paper.pdf) it would results in `dmb.sy` but I assume the paper intended to cover the cases `!= acq` **and rx!!!**.

I will follow up this discussion with genmc folks. Thanks for pointing that to me!

> Coming back to the real code, how do `a_inc`, `a_sub` and `a_cas` related to `atomic_fetch_add_explicit`, `atomic_fetch_sub_explicit ` and `atomic_compare_exchange_strong_explicit`? From e.g., [here](https://fossies.org/dox/musl-1.2.2/arm_2atomic__arch_8h_source.html) it seems they are plain inlined assembly. But I don't see how they can handle atomic instructions with different memory orderings, e.g., how do you differentiate `atomic_fetch_add_explicit(&m->waiters, 1, memory_order_relaxed)` from `atomic_fetch_add_explicit(&m->waiters, 1, memory_order_seq_cst)`?

I am concerned with the `a_barrier`, which is a `dmb ish`, in the `a_cas` (see [here](https://fossies.org/dox/musl-1.2.2/aarch64_2atomic__arch_8h_source.html#l00023)). I think they try to force a release barrier on the failure case of the CAS, but I am not sure how useful that is. Anyway, since the musl mutex is inherited from GenMC, let me stop pointing to weird things :-) The code serves its purpose of testing your tool. Just be aware that it may not reflect the barrier choices of the real musl mutex.

Thanks for taking a look!
