### ISSUE TITLE
Detecting Liveness of Spinloops

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#173]
Dartagnan can only handle reachability right now. However, in practice this is not enough to guarantee correct code since deadlock situations may occur. To prevent those, one often has to place stronger barriers than are needed for plain reachability.
In other words: "Practically correct == Safe + Terminating" and we only do the safeness aspect right now.

According to [this](https://arxiv.org/abs/2012.01067) liveness can be understood even in axiomatic models. But the practical idea is more easily understood via [Vsync](https://people.mpi-sws.org/~viktor/papers/asplos2021-vsync.pdf).

Let me explain the overall concept.
A partial execution is _stagnant_ iff all non-terminated threads are inside an await/spin-loop that they cannot exit with read values available to them (such an execution will never terminate!)
In the axiomatic case, the idea of "available values" can be understood via the existence of writes that are co-later than the last write the spin-loop read from. This is because a spinloop should always have the possibility to observe _newer_ writes eventually (this holds assuming a notion of _memory fairness_ where e.g. no stores are indefinitely buffered).
So for any stagnant execution there will also exist a stagnant execution where all looping threads read **only** the co-maximal writes(*).

Based on this observation, we can formulate liveness of spinloops as follows. 
A program in which all unbounded loops are spinloops is non-terminating IFF there exists a consistent execution such that one spinloop reads from a co-maximal write without leaving the loop(**).
Furthermore, as spinloops do not produce any values, we can bound all spinloops to run only once (i.e. always assume unrolling bound = 1). In this case, a spinloop is stagnant if it reads a co-maximal write AND also reaches its bound event (this indicates that the loop was not left).

Implementation:
- The encoding of reading co-maximal writes can be done by reusing the `lastCo` variable we already create for litmus tests.
- The bigger problem is detecting spinloops and being able to unroll them only once. We need more code that handles program analysis and transformation.
- Unlike reachability, for liveness we have to return UNKNOWN if any non-spinloop is not sufficiently unrolled. This is because the values that such a loop produces could do both (1) allow termination of stuck spinloops or (2) allow the possibility of non-termination by providing a new co-maximal write that causes stagnation. So we have two notions of UNKNOWN in the form of "seems non-terminating but not sure" and "seems terminating but not sure".

(*) We need the assumption that once a thread observes some write, no future read can observe a co-previous write anymore. This should be given by SC-per-Loc and hence always hold for all reasonable models.

(**) WRONG (see next comment)
Note that in the axiomatic setting, if there was another thread that is not stuck and that can produce a new write value that would lead to termination of some other stuck spin-loop, then that spin-loop would not have read a co-maximal write!
It is only in an operational setting like SMC where one has to consider ALL running threads simultaneously with the current co-maximal values of the partial execution (our axiomatic executions are never partial!)

**Comment by ThomasHaas** [comment]
Correction:

We need to check the maximality condition for **all** spinloops that reach its bound event instead of a single one.
Otherwise a single spinloop may spuriously fail by reading an outdated value, which in turn prevents generation of new events that could allow a different spinloop to terminate, falsely leading to a non-termination verdict.

In other words: We look for an execution such where each spinloop that hits its bound event also reads a co-maximal value (
`For all i: (boundReach_i => exists w: rf(w, r_i) & lastCo(w))`) where `boundReach_i` and `r_i` refer to the bound/read(s) of the i-th spinloop.

**Comment by hernanponcedeleon** [comment]
This is already implemented in `development`
