### ISSUE TITLE
Passing include path to clang and smack

### ISSUE THREAD

**Issue by db7** [hernanponcedeleon/Dat3M#174]
Is there a way how pass `-I path/to/include` options to clang and smack? I am trying to check a small program that depends on some header files, and such an option would be nice (an environment variable could be even more flexible).  I found in the source code that `Dat3M/include` is passed to the compiler, but moving my files into that directory didn't help.

**Comment by hernanponcedeleon** [comment]
> an environment variable could be even more flexible

Would something like `CFLAGS` work for you?

**Comment by hernanponcedeleon** [comment]
A fix has been pushed to the `development` branch with a93de3333c610ab4aa8bc53e3c3c439055b7c7d5.
@db7 the docker container uses this branch by default, thus running `git pull; mvn clean install -DskipTests` should be enough to get the latests version.
You should be able to set the path (and use any further compiler flags you need) by setting `CFLAGS` in your environment.

**Comment by db7** [comment]
Great! Thank you for the quick action!
