### ISSUE TITLE
Alias analysis options

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#187]
Despite having three alias analysis options (NONE, CFS, CFIS), we always use CFS.
As expected NONE will always perform worse (I tested it and it is the case).
The idea is that CFIS is more expensive to compute, but it should reduce more (this is not the case for the benchmarks I checked). 
It might be that this is because we have "optimised" alias analysis but only for CFS.
In terms of performance, CFIS seems to not be worth it: for Clock the overhead is ~30% and for svcomp-concurrency is ~10%.
Since we always make use of CFS, I think we should get rid of the other code to simplify our codebase.
What do you think @ThomasHaas and @xeren?

**Comment by ThomasHaas** [comment]
I'm fine with that.
