### ISSUE TITLE
Interface for exec-implication

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#207]
We have a lot of code that does reasoning based on whether the execution of one event implies the execution of another event.
Currently we use cf-implications from `BranchEquivalence` and lift them up to exec-implications by checking `cfImpliesExec`.
But this has two disadvantages:
1) Most code is only interested in exec-implications but to get them, it has to deal with the nuisance of using cf-implications and lifting them. Many times this has lead to errors because e.g. `cfImpliesExec` was not checked properly.
2) Apart from cf-based reasoning, there are far more reasons that could imply the execution of certain events. For example any sort of assumptions or witnesses will provide events that are guaranteed to execute. Also the specification might imply the execution of certain events (e.g., if we have only one assertion, then each violating execution has to at least execute that assertion).
We can also reason about value-flow in a producer-consumer setting where the consumer code only runs if the producer produced a certain value. In particular, our thread-creation code is of this shape: A spawned thread can only execute if it reads a value produced by `pthread_start`, implying that this `pthread_start` was executed.

So we should add an abstraction layer (an interface) that provides this information. Currently, the only implementation would use `BranchEquivalence` and `cfImpliesExec`, but in the future we could extend this easily with more information without changing any calling code.

**Comment by hernanponcedeleon** [comment]
Can we close?

**Comment by ThomasHaas** [comment]
yes
