### ISSUE TITLE
LKMM reference

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#211]
On the Linux github repo, there is a very detailed section about its memory model [LKMM](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/memory-model).
Importantly,
- it contains the official `.cat` file for linux kernel memory model.
- There is a lot of documentation about the memory model in natural language (to understand the intentions of the .cat file).
- There is documentation about how to use `herd7` on `C-litmus` tests and what they can and cannot model. In particular, some discrepancies between the formal memory model and the actual memory model are explained. 

I think for all questions regarding the LKMM, this is the first source we should check out.

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
