### ISSUE TITLE
New LFDS benchmarks

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#250]
The benchmarks are already written in C so we probably only need to write some client code.

Stack: https://github.com/skeeto/lstack
Queue: https://github.com/skeeto/scratch/blob/master/misc/queue.c

**Comment by ThomasHaas** [comment]
The stack requires a double-width CAS, which we don't support (yet). 
The queue might be doable, but it has a lot of bit vector reasoning.

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
