### ISSUE TITLE
Problem with RemoveDeadCondJumps pass

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#329]
If CP is enabled, the assertion in [this benchmark](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/pthread-demo-datarace-2.c/c/pthread-C-DAC/pthread-demo-datarace-2.c) is completely removed, making the program trivially safe (which is not).

**Comment by ThomasHaas** [comment]
Can you confirm that it was really CP or if it was the pass that removes dead jumps after CP?
IIRC, it was not CP itself that was buggy.

**Comment by hernanponcedeleon** [comment]
Indeed, the problem disappears if we remove that pass

**Comment by hernanponcedeleon** [comment]
I think I found the problem and it was not really related to the pass, but rather that solvers have this `Verification finished: property trivially holds` feature.

This snippet already shows the problem (i.e. we return PASS)
```
#include <assert.h>
#include <pthread.h>

int myglobal; 

int main(void)
{
    for (int i=0; i<20; i++) { myglobal++; }
    assert(myglobal == 40);
}
```
which results in the following boogie code
```
(20)  0:$bb1:
(21)     0:$i1 <- 0:$i0 < 20
(24)     if((! 0:$i1 == 1)); then goto 0:$bb3:
(25)     0:$i2 = load(*myglobal)
(26)     0:$i3 <- (0:$i2 + 1)
(27)     store(*myglobal, 0:$i3)
(30)     0:$i4 <- (0:$i0 + 1)
(31)     0:$i0 <- 0:$i4
(32)     goto 0:$bb1:
(33)  0:$bb3:
(34)     if((! (! 0:$i1 == 1))); then goto END_OF_T1:
(37)     0:$i5 = load(*myglobal)
(38)     0:$i6 <- 0:$i5 == 40
(41)     if((! 0:$i6 == 1)); then goto 0:$bb8:
(42)     goto 0:$bb7:
(43)  0:$bb8:
(44)     if((! (! 0:$i6 == 1))); then goto END_OF_T1:
(45)     assert_0 <- 0
(46)     if(assert_0 != 1); then goto END_OF_T1:
(48)  0:$bb7:
(53)  END_OF_T1:
```
CP says that the condition of 24 is false and thus this event gets removed. Because 32 is unconditional and 24 was removed, 33 becomes dead code. The whole block gets removed making 45 dead. Since the program has no assertion, we return PASS.

I think the simplest solution is to remove the part of all solvers not starting the verification if the program has no assertions (I don't think this was giving any real performance boost). This will force the solver to always check if the program has been fully unrolled.

**Comment by ThomasHaas** [comment]
I'm fine with removing the early termination in case of no assertion.
