### ISSUE TITLE
SVCOMP properties

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#342]
SVCOMP rules require that the verification starts for at least 50% of the tasks.
Now that `no-overflow` and `mem-safety` has been added as part of the concurrency category, we need to return `UNKNOWN` instead of throwing a parsing exception for those property.

**Comment by hernanponcedeleon** [comment]
We could still rely on the file name and make SVCOMPRunner return UNKNOWN, but maybe we should take the chance in add some parsing of the content

**Comment by ThomasHaas** [comment]
A quick&dirty fix is good enough for now, unless you have an easy way to add proper parsing.
IIRC proper parsing is also needed to work with the CoVeriTeam online service cause that one generates property files with temporary names.

**Comment by hernanponcedeleon** [comment]
This year we qualified even if we failed to parse the properties (I explained to the jury that we don't support such properties and this could easily be fixed and they agreed on qualification).

I am adding this issues as a reminder that we need to solve this before next year, but we have enough time to add some proper parsing

**Comment by hernanponcedeleon** [comment]
Implemented by 6d75773 and 579daf2
