### ISSUE TITLE
Supporting .cats with redefinitions

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#367]
Herd7 supports .cat files that (re-)define a relation multiple times:
```
let x = po | rf
let y = x \ co
let x = x | data // redefines x, equivalent to "let x_2 = x | data"
let y = x & y // equivalent to "let y_2 = x_2 & y"
```
As can be seen from the example, we can change a .cat with redefinitions to one without by using a kind of SSA form.
We can implement this automatic renaming in our parser (every redefinition results in a new and unique relation).

Implementation notes:
- The parsing, and hence renaming, needs to be done top-down. 
- We can just attach a numeric suffix to redefinitions.
- One needs to distinguish redefinitions `let x = x ...` from recursive definitions `let rec x = x ...`
- The rhs of a redefinition needs to be parsed first to avoid accidentally creating recursive definitions.
- We may or may not allow for a redefinition to be recursive. In case we allow for it, we have to be careful with the parsing order
  ```
  let x = ....;
  let rec x = x | y // Equivalent to "let rec x_2 = x_2 | y" and NOT "let rec x_2 = x_1 | y"
  ```

**Comment by hernan-poncedeleon** [comment]
Already implemented
