### ISSUE TITLE
Collection of loops for spinloop detection / verification

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#370]
The idea of this issue of to collect different examples of loops that should or should not be considered spinloops for liveness detection.

I will keep one code example per msg so we can discuss each of them by answering the corresponding msg.

**Comment by hernanponcedeleon** [comment]
```
	do {
		owner = *p;
	} while (cmpxchg_relaxed(p, owner,
				 owner | RT_MUTEX_HAS_WAITERS) != owner);
```
coming from [rtmutex implementation](https://github.com/torvalds/linux/blob/master/kernel/locking/rtmutex.c#L237) in the linux kernel.

**Comment by hernanponcedeleon** [comment]
```
	rcu_read_lock();
	for (;;) {
		/* If owner changed, trylock again. */
		if (owner != rt_mutex_owner(lock))
			break;
		/*
		 * Ensure that @owner is dereferenced after checking that
		 * the lock owner still matches @owner. If that fails,
		 * @owner might point to freed memory. If it still matches,
		 * the rcu_read_lock() ensures the memory stays valid.
		 */
		barrier();
		/*
		 * Stop spinning when:
		 *  - the lock owner has been scheduled out
		 *  - current is not longer the top waiter
		 *  - current is requested to reschedule (redundant
		 *    for CONFIG_PREEMPT_RCU=y)
		 *  - the VCPU on which owner runs is preempted
		 */
		if (!owner_on_cpu(owner) || need_resched() ||
		    !rt_mutex_waiter_is_top_waiter(lock, waiter)) {
			res = false;
			break;
		}
		cpu_relax();
	}
```
coming from [rtmutex implementation](https://github.com/torvalds/linux/blob/master/kernel/locking/rtmutex.c#L1405) in the linux kernel.

**Comment by hernanponcedeleon** [comment]
```
#define smp_cond_load_relaxed(ptr, cond_expr) ({        \
      typeof(ptr) __PTR = (ptr);                        \
      __unqual_scalar_typeof(*ptr) VAL;                 \
      for (;;) {                                        \
          VAL = READ_ONCE(*__PTR);                      \
          if (cond_expr)                                \
              break;                                    \
          cpu_relax();                                  \
      }                                                 \
      (typeof(*ptr))VAL;                                \
})
```

Defined [here](https://elixir.bootlin.com/linux/latest/source/include/asm-generic/barrier.h#L248) and used by [qspinlock](https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L554).

**Comment by hernanponcedeleon** [comment]
```
for (;;) {
	new = (val & _Q_LOCKED_PENDING_MASK) | tail;
	/*
	 * We can use relaxed semantics since the caller ensures that
	 * the MCS node is properly initialized before updating the
	 * tail.
	 */
        old = atomic_cmpxchg_relaxed(&lock->val, val, new);
	if (old == val)
		break;

	val = old;
}
```
Also coming from [qspinlock](https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L225).

**Comment by hernanponcedeleon** [comment]
We also need to take a look to the examples in [this paper](https://arxiv.org/abs/2208.09259) and the plp benchmakrs [here](https://github.com/nidhugg/nidhugg/tree/master/tests/smoke/C-tests)

**Comment by ThomasHaas** [comment]
All the standard await example are trivial.
There are some examples with the name `xchgawait`, but they all rely on some custom function
```int __VERIFIER_xchg_await_aint(atomic_int *var, int value, int cond, int comp_operand);```
which is likely just a CAS-loop that they do not detect otherwise.
Overall, pretty trivial benchmarks IMO.

**Comment by ThomasHaas** [comment]
Oh, I missed all the `plp` benchmarks and only looked at the older one's... Those might be more interesting indeed.

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
