### ISSUE TITLE
Verification of Linux Kernel Loop (rtmutex) (2)

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#373]
```
	for (;;) {
		/* If owner changed, trylock again. */
		if (owner != rt_mutex_owner(lock))
			break;
		/*
		 * Ensure that @owner is dereferenced after checking that
		 * the lock owner still matches @owner. If that fails,
		 * @owner might point to freed memory. If it still matches,
		 * the rcu_read_lock() ensures the memory stays valid.
		 */
		barrier();
		/*
		 * Stop spinning when:
		 *  - the lock owner has been scheduled out
		 *  - current is not longer the top waiter
		 *  - current is requested to reschedule (redundant
		 *    for CONFIG_PREEMPT_RCU=y)
		 *  - the VCPU on which owner runs is preempted
		 */
		if (!owner_on_cpu(owner) || need_resched() ||
		    !rt_mutex_waiter_is_top_waiter(lock, waiter)) {
			res = false;
			break;
		}
		cpu_relax();
	}
```
coming from [rtmutex implementation](https://github.com/torvalds/linux/blob/master/kernel/locking/rtmutex.c#L1405) in the linux kernel.

_Originally posted by @hernanponcedeleon in https://github.com/hernanponcedeleon/Dat3M/issues/370#issuecomment-1400393445_

**Comment by ThomasHaas** [comment]
It is hard to judge this loop, because none of the called functions are defined in [rtmutex implementation](https://github.com/torvalds/linux/blob/master/kernel/locking/rtmutex.c#L1405).
Assuming they all just perform some sort of read (judging by the names), we should detect this as a prototypical spin loop (side-effect free, 1-bounded).

**Comment by hernanponcedeleon** [comment]
The implementation of `rt_mutex_owner` is [here](https://github.com/torvalds/linux/blob/master/kernel/locking/rtmutex_common.h#L136). 

Tha file also defines `rt_mutex_waiter_is_top_waiter`, but then it makes some calls to the rbtree API.

That being said, the bpl file in #369 contains this call, so we can effectively test if we automatically recognize the spinloop.

**Comment by ThomasHaas** [comment]
The implementation of `rt_mutex_owner` is no problem for liveness, and `rt_mutex_waiter_is_top_waiter` also looks fine.
However, the implementation already shows problems for our alias analysis:
```
static inline struct task_struct *rt_mutex_owner(struct rt_mutex_base *lock)
{
	unsigned long owner = (unsigned long) READ_ONCE(lock->owner);

	return (struct task_struct *) (owner & ~RT_MUTEX_HAS_WAITERS); // Bit-fiddling on pointer
}
```

**Comment by hernanponcedeleon** [comment]
Is the problem with the alias analysis related to "Bit-fiddling on pointer"? Was this the same problem we had with harris list?

**Comment by ThomasHaas** [comment]
Let's move the alias analysis discussion to the appropriate issue #369.

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
