### ISSUE TITLE
Verification of Linux Kernel Loop (qspinlock)

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#379]
```
#define smp_cond_load_relaxed(ptr, cond_expr) ({        \
      typeof(ptr) __PTR = (ptr);                        \
      __unqual_scalar_typeof(*ptr) VAL;                 \
      for (;;) {                                        \
          VAL = READ_ONCE(*__PTR);                      \
          if (cond_expr)                                \
              break;                                    \
          cpu_relax();                                  \
      }                                                 \
      (typeof(*ptr))VAL;                                \
})
```

Defined [here](https://elixir.bootlin.com/linux/latest/source/include/asm-generic/barrier.h#L248) and used by [qspinlock](https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L554).

_Originally posted by @hernanponcedeleon in https://github.com/hernanponcedeleon/Dat3M/issues/370#issuecomment-1403525576_

**Comment by ThomasHaas** [comment]
The characterization of this loop totally depends on what `cond_expr` is.
IIRC, in qspinlock `cond_expr` is side-effect full (doing something like `cnt++`).
But we need more information to analyze this loop.

**Comment by hernanponcedeleon** [comment]
Here are a few uses of the macro from the kernel (the different "variants" are just wrappers or alias around the relax version)
- https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L554
- https://elixir.bootlin.com/linux/latest/source/kernel/locking/mcs_spinlock.h#L34
- https://elixir.bootlin.com/linux/latest/source/kernel/locking/qrwlock.c#L33
- https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L383
The latest two are probably the most interesting ones

**Comment by ThomasHaas** [comment]
> https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L554
https://elixir.bootlin.com/linux/latest/source/kernel/locking/mcs_spinlock.h#L34
https://elixir.bootlin.com/linux/latest/source/kernel/locking/qrwlock.c#L33
https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L383

All of them are typical spinloops that we should detect statically.

**Comment by ThomasHaas** [comment]
This instance https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L338 is one which is more interesting, due to the bounded waiting. I don't think there is anything we can do about it.
While it cannot spin due to the bounded waiting, one could argue that waiting just once is sufficient to explore all necessary behaviour.

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
