### ISSUE TITLE
Verification of Linux Kernel Loop (qspinlock) (2)

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#380]
```
for (;;) {
	new = (val & _Q_LOCKED_PENDING_MASK) | tail;
	/*
	 * We can use relaxed semantics since the caller ensures that
	 * the MCS node is properly initialized before updating the
	 * tail.
	 */
        old = atomic_cmpxchg_relaxed(&lock->val, val, new);
	if (old == val)
		break;

	val = old;
}
```
Also coming from [qspinlock](https://elixir.bootlin.com/linux/latest/source/kernel/locking/qspinlock.c#L225).

_Originally posted by @hernanponcedeleon in https://github.com/hernanponcedeleon/Dat3M/issues/370#issuecomment-1403530137_

**Comment by ThomasHaas** [comment]
- The loop has 2-bounded side-effects (unrolling bound = 2 is enough)
- This loop cannot deadlock (CAS-loops cannot really deadlock)
- We do not detect the 2-boundedness, neither statically nor dynamically.

**Comment by hernanponcedeleon** [comment]
It seems that from all spinloops in qspinlock, this is the only one that we cannot currently detect, but as you say, this should not affect the correctness of our liveness results.

**Comment by ThomasHaas** [comment]
The only negative consequence on liveness detection is that we will report `UNKNOWN` rather than `PASS`.
But we certainly do not miss a potential deadlock.

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
