### ISSUE TITLE
Distinguishing boolean and integer registers

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#39]
When compiling C code to LLVM IR, booleans may end up as i8 (8-bit integers). Encoding them as such is unnecessary and puts more reasoning onto the theory-solver. Encoding them as pure propositonal values may give significant benefit.

Similarly, instrumentations of C code/LLVM code may use suboptimal types for introduced variables (e.g. int32 instead of bool). Automatic detection of bools via static analysis also addresses this problem as a side-effect.

**Comment by hernanponcedeleon** [comment]
Fixed in #478
