### ISSUE TITLE
References for concurrent data structures

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#394]
I found two interesting repos containing a wide range of concurrent data structures, both locked and lock-free.
Maybe there are some examples we can extract.

[Synchrobench](https://github.com/gramoli/synchrobench)

[ASCYLIB](https://github.com/LPD-EPFL/ASCYLIB)

**Comment by hernanponcedeleon** [comment]
[This](https://github.com/parapluu/lock_benchmarking) might contain several benchmarks almost ready to use

**Comment by hernanponcedeleon** [comment]
Closing resource issues. They will remain available even if closed.
