### ISSUE TITLE
Compilation & Unrolling

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#43]
Currently, we first unroll and then compiler.
However there are compilation schemes that may introduce loops.
Thus we need to first compile and then unroll.
In its current form, the passes cannot be re-ordered because they throw exceptions

**Comment by ThomasHaas** [comment]
Reversing the order of unrolling and compilation is not easy. Some compilation introduces paired events like `RMWStore` + `RMWLoad` or `ExecutionStatus` + `StoreExclusive` whose pairing needs to be updated on unrolling.

**Comment by hernanponcedeleon** [comment]
This kind of relation is similar to what we have between `CondJump` and `Label`, isn't it? If it is the case, we can use the `listener` mechanism

**Comment by ThomasHaas** [comment]
Yes, it is similar and you can reuse the listener mechanism. It's just that it is a lot easier to copy a single complex event than to copy multiple simple but related events. 
Do we actually need that anymore? I think the only compilation scheme that introduced loops was that one for strong CAS, but we got rid of that. Is there any other compilation that creates loops? And even if there is, if those loops do not cause visible side effects (which I guess should always be true), we can direcly compile to a version that with only the last iteration (similiar to spinlock-optimization)

**Comment by hernanponcedeleon** [comment]
We don't have loop-introducing compilation schemes anymore. I'll close.
