### ISSUE TITLE
Nondeterministic expressions in Loops show wrong behaviour

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#454]
Multiple events that refer to the same non-det expression will produce the same non-determinstic value in the same execution.
This is a problem when unrolling loops like this:
```
int x = 0;
while (x != 5) {
  if (__VERIFIER_nondet_int() == 0) {
     x += 2;
  } else {
     x += 3;
  }
}
assert (0); // Should be reachable, but we fail to detect it.
```
The non-deterministic choice will be made only once and then all iterations take the same branch, so that the loop will never terminate.

We need to give non-deterministic expressions special handling and either
(1) make sure to create new nondet expressions instances when unrolling loops
OR (2) create different logical variables at each event (i.e., create a variable per `<nondet expr, event>` pair).
The latter solution is not so nice because it disallows constant propagation of nondet expressions.

I think this problem also shows that we need to distinguish between nondet expressions and program constants (which may also have non-deterministic values), cause the former needs to change during code duplication while the latter does not.

**Comment by hernanponcedeleon** [comment]
This should be fixed already (by #485 I believe). @ThomasHaas can we close?
