### ISSUE TITLE
[BUG] Incorrect RA computation for setminus relation

### ISSUE THREAD

**Issue by natgavrilenko** [hernanponcedeleon/Dat3M#523]
In a setminus relation, the superset should have a dependency to the complement to ensure correct computation of (regular) relation analysis sets.

Scenario:
- May and must sets computed for the superset (complement hasn't been processed yet).
- May and must sets of the superset are copied to the may and must sets of the parent setminus relation.
- May and must sets computes for the complement.
- May and must sets of the setminus relation (and its parents) are not reduced according to the information from the complement (propagation always increments sets).

Impact:
- Not updating may set in a setminus relation can lead to unnecessary computation.
- Not updating must set in a setminus relation can lead to an incorrect verification result.

Possible solutions:
- Add a dependency a superset to the complement to ensure that the complement is computed first.
- Propagate decremental updates to a setminus and its parent relations.

**Comment by ThomasHaas** [comment]
The "decremental updates" solution is not going to work: decremental updates are a lot harder to do in general and AFAIK impossible in recursive relations.
A temporary solution with a (fake) dependency seems to be the best for now.

A more sophisticated solution is by not "propagating" at all and instead computing the may/must set of a relation only once all its dependencies are computed already (except in the case of recursion, but then there cannot be set differences inside the stratum). This was how it was originally done and it should also be more efficient anyway.

**Comment by natgavrilenko** [comment]
Yes, I agree, precomputing will be the best solution.

**Comment by ThomasHaas** [comment]
We have a temporary workaround code implemented since #524 . We should still keep this issue open.

**Comment by hernanponcedeleon** [comment]
We this issue be closed now?

**Comment by ThomasHaas** [comment]
I guess we can close it.
