### ISSUE TITLE
Mixing inline assertions with litmus-style assertions is buggy

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#54]
The code that *should* combine both types of assertions does only consider litmus-style assertions if present.
This is a simple mistake in the call to ctx.mkAnd() in VerificationTask.encodeAssertions():

**Comment by hernanponcedeleon** [comment]
Solved by 46ac4efd6ddad48a905f0250eeb1f1b738105e54
