### ISSUE TITLE
Dockerfile failed to build maven

### ISSUE THREAD

**Issue by DerGrumpf** [hernanponcedeleon/Dat3M#610]
The Goal `org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile` compile failed with error `invalid target release: 17`.

Is there any fix? Trying to use the master branch in the `git clone` command doesn`t change anything.

**Comment by ThomasHaas** [comment]
Hi DerGrumpf,
it seems that the docker image loads java version 11 (openjdk11) but we have updated Dartagnan to require version 17+.
@hernanponcedeleon Do you know how to update the java version in the docker?
I think adding 
```
apt install openjdk-17-jdk-headless
```
OR
```
apt install openjdk-17-jdk openjdk-17-jre
```
might already do the trick?

**Comment by DerGrumpf** [comment]
Haha Yes thx. I update the File for you :)

**Comment by DerGrumpf** [comment]
nvm i didn't have the rights to open a new branch ...

Just add `apt-get install -y openjdk-17-jdk && \ apt-get install -y openjdk-17-jre` after the install RUN command.
