### ISSUE TITLE
Unexpected liveness violation

### ISSUE THREAD

**Issue by db7** [hernanponcedeleon/Dat3M#647]
The attached file 
[test.ll.txt](https://github.com/hernanponcedeleon/Dat3M/files/14965701/test.ll.txt)
gives unexpected results with dat3m.

> Note I had to rename the file as `test.ll.txt` to make github accept it, you might want to remove the `.txt` suffix.

I'm using this command to run the file:
```
java -jar /usr/share/dat3m/dartagnan/target/dartagnan.jar \
  test.ll \
  --property=program_spec,liveness \
  --modeling.threadCreateAlwaysSucceeds=true \
  --encoding.wmm.idl2sat=true \
  --solver=yices2 \
  --target=imm \
  /usr/share/dat3m/cat/imm.cat \
  --bound=5
```

This is the [commit](https://github.com/hernanponcedeleon/Dat3M/commit/b57432899) I'm using.

The output of the command above tells me:

```
[13.04.2024] 07:55:22 [INFO] RefinementSolver.runInternal - Specification violation found.
[13.04.2024] 07:55:22 [INFO] RefinementSolver.runInternal - Summary
 ======== Summary ========
Number of iterations: 3
Total native solving time: 1.632 secs
   -- Bound check time: 0.0 secs
Total CAAT solving time: 0.169 secs
   -- Model extraction time: 0.29 secs
   -- Population time: 0.106 secs
   -- Consistency check time: 0.1 secs
   -- Reason computation time: 0.25 secs
   -- Refining time: 0.25 secs
   -- #Computed core reasons: 28
   -- #Computed core reduced reasons: 26
   -- Min model size (#events): 44
   -- Average model size (#events): 48
   -- Max model size (#events): 51

[13.04.2024] 07:55:22 [INFO] RefinementSolver.runInternal - Verification finished with result FAIL
============ Liveness violation found ============
	E923:	@check-spsc.c#40
=================================================
FAIL
Total verification time: 11.627 secs
```

Now, also interesting is that if I use bound == 6, the output of dat3m changes, giving me a program spec violation.

```
[13.04.2024] 08:00:30 [INFO] RefinementSolver.runInternal - Specification violation found.
[13.04.2024] 08:00:30 [INFO] RefinementSolver.runInternal - Summary
 ======== Summary ========
Number of iterations: 17
Total native solving time: 4.577 secs
   -- Bound check time: 0.0 secs
Total CAAT solving time: 0.370 secs
   -- Model extraction time: 0.108 secs
   -- Population time: 0.169 secs
   -- Consistency check time: 0.1 secs
   -- Reason computation time: 0.58 secs
   -- Refining time: 0.150 secs
   -- #Computed core reasons: 101
   -- #Computed core reduced reasons: 67
   -- Min model size (#events): 30
   -- Average model size (#events): 55
   -- Max model size (#events): 62

[13.04.2024] 08:00:30 [INFO] RefinementSolver.runInternal - Verification finished with result FAIL
===== Program specification violation found =====
	E113:	@check-spsc.c#70: user assertion
=================================================
FAIL
Total verification time: 27.352 secs
```

## Questions

- Is the liveness violation here ok? or a bug? (GenMC does not report it with `-imm -check-liveness`) 
- Is it ok that increasing the bound may change the detected violation?

**Comment by ThomasHaas** [comment]
I cannot reproduce the liveness verdict (I get UNKNOWN), but your code loads from uninitialized memory which causes Dartagnan to report a warning:
Here is the LLVM-snippet:
```
define dso_local i8* @consumer(i8* noundef %0) #0 !dbg !156 {
1:
	%2 = alloca i8*, align 8
	%3 = alloca i32, align 4 // <---- Fresh allocation
	%4 = alloca %struct.data*, align 8
	store i8* %0, i8** %2, align 8
	call void @llvm.dbg.declare(metadata i8** %2, metadata !157, metadata !DIExpression()), !dbg !158
	call void @llvm.dbg.declare(metadata i32* %3, metadata !159, metadata !DIExpression()), !dbg !161
	br label %5, !dbg !162

5:
	%6 = load i32, i32* %3, align 4, !dbg !163 // <---- Load from uninitialized allocation
```
This may not be the culprit for Dartagnan's verdict, but I think you should fix the code still :).

**Comment by db7** [comment]
@ThomasHaas That's a great catch! I didn't look into the warnings and messages of dartagnan (it's a bit verbose). The unintialized-access warning is probably this:
```
[13.04.2024] 12:30:19 [WARN] Dependency.process - Uninitialized register bv32 DUMMY_REG_1 read by event bv1 r7 <- ITE((bv32 DUMMY_REG_1 < bv32(3)), bv1(1), bv1(0)) of thread 2
```
And it was caused by this:
```c
for (int i; i < MAX; i++)
   ...
```

I'll keep an eye for that. It's super useful. And it is also quite strange GenMC didn't complain. Thanks for investigating it!

**Comment by ThomasHaas** [comment]
> @ThomasHaas That's a great catch! I didn't look into the warnings and messages of dartagnan (it's a bit verbose). The unintialized-access warning is probably this:
> 
> ```
> [13.04.2024] 12:30:19 [WARN] Dependency.process - Uninitialized register bv32 DUMMY_REG_1 read by event bv1 r7 <- ITE((bv32 DUMMY_REG_1 < bv32(3)), bv1(1), bv1(0)) of thread 2
> ```

Yes, it's that one. Most logging output was intended for internal use (and so is verbose/not user-friendly) but I guess we could make this warning a bit more user-friendly by also printing the C source location (if available).
Actually, we wouldn't even have catched that bug if our internal `mem2reg` pass didn't promote the stack allocation to a register, because for historical reasons we assume a default value of 0 in memory but use non-determinstic one's for registers.

> And it was caused by this:
> 
> ```c
> for (int i; i < MAX; i++)
>    ...
> ```
> 
> I'll keep an eye for that. It's super useful. And it is also quite strange GenMC didn't complain. Thanks for investigating it!
