### ISSUE TITLE
Implement Assume event

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#65]
Create an event having the usual verification assume semantics, i.e. filtering those executions where the input expression is false

**Comment by hernanponcedeleon** [comment]
Fixed by 3fea22a2f3dab20f3d9682184f729f22873e6830, 2ac4cb1ceaf180d4c3807a6782d13c0723b7be62 and 8c099fbd644d611936b15fe27275c23b087d6e82.

**Comment by ThomasHaas** [comment]
This was fixed as part of #103 and is now integrated into development.
