### ISSUE TITLE
Allow modular C files from UI

### ISSUE THREAD

**Issue by hernanponcedeleon** [hernanponcedeleon/Dat3M#66]
Currently, C files used from the UI must have all code in a single file (the loaded one).
We should allow the compiler to detect all files from the same directory from where the file was loaded.

**Comment by hernanponcedeleon** [comment]
Solved by 9b939cd0d25be48a76c0b20772aa531838d98adc

**Comment by ThomasHaas** [comment]
Can this get closed?

**Comment by hernanponcedeleon** [comment]
Yes
