### ISSUE TITLE
Replacing TupleSet

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#68]
Context: RIght now we use a custom class TupleSet to manage sets of tuples/edges

Problems: 
-  It is impossible to extend TupleSet with implementations that are better suited for certain cases
-  Existing set-based functions like those provided by google.guava do not integrate nicely

Solutions:
- Replace TupleSet by an interface and use the current implementation as a default implementation (addresses only problem 1)
- Get rid of it entirely and use Set<Tuple> instead to maximise usability of existing code. The additional features of TupleSet may be moved to a utility class instead.

**Comment by hernanponcedeleon** [comment]
I think this is solved now, right @ThomasHaas ?

**Comment by ThomasHaas** [comment]
Yes, it is solved.
