### ISSUE TITLE
Reflexive closures

### ISSUE THREAD

**Issue by ThomasHaas** [hernanponcedeleon/Dat3M#70]
Problem: Right now, reflexive closures get replaced by unions: po? becomes po | id. On the other hand, we have a dedicated relation for the reflexive, transitive closure: r* does not become r^+ | id.

Solutions:
(1) Replace r* by r^+ | id to make everything consistent.
(2) Introduce a true reflexive closure. This could be handled more efficiently than the union.

**Comment by hernanponcedeleon** [comment]
I think @xeren did some re-writing related to that. If so, can this be closed?

**Comment by ThomasHaas** [comment]
Yep, this seems to be done.
