### ISSUE TITLE
problem with llvm parser

### ISSUE THREAD

**Issue by StefanoDalMas** [hernanponcedeleon/Dat3M#757]
The parser is not recognising this attached file
[ttaslock.ll.zip](https://github.com/user-attachments/files/17412932/ttaslock.ll.zip)

**Comment by ThomasHaas** [comment]
#758 fixes the issue. The parser will still complain about unsupported inline assembly though.

**Comment by hernanponcedeleon** [comment]
> #758 fixes the issue. 

Thanks for the quick fix Thomas :rocket:

> The parser will still complain about unsupported inline assembly though.

Yes, we know. Stefano will be working on adding support for that.
